### ISSUE TITLE
How to deal with assays without names?

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/footprintR#12]
- What should `.getReadLevelAssayNames()` return? The index of the assay(s)? What if some assays are named and others not? 
- Or should we just require that all assays are named (even though `SummarizedExperiment` doesn't impose such requirements)?

**Comment by mbstadler** [comment]
Good point! What about replacing `.getReadLevelAssayNames()` by `.getReadLevelAssayIndices()`, so we don't have to impose anything on top of `SummarizedExperiment`? It seems that the change would be not so big. `.getReadLevelAssayNames()` is only used three times: in `.checkSEValidity`, its unit test and `subsetReads`, and it seems to me that all these cases can also use an index returned from it.

**Comment by csoneson** [comment]
Yes, I think we can do that. We should probably add some tests for the functions that specify `assay.type` as well, to make sure they do the right thing.

**Comment by csoneson** [comment]
All assays are now required to be named, implemented in https://github.com/fmicompbio/footprintR/commit/4c51458376a686a78590422b1379031471f8010b
