### ISSUE TITLE
Read filtering

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/footprintR#15]
- [x] quality score (why/how is it different from what is returned by dorado?) - hard threshold at 10 (default)
- [x] KS entropy
- [x] fraction of low-confidence modified base calls (fail rate)
- [x] read length/aligned length/fraction aligned
- [x] remove reads that are NA in all positions
- [x] call position-NA-filtering in the end (by default turned on) to remove positions that are now all NA

**Comment by csoneson** [comment]
Mostly done in ce3742402e3a661e22b655be41d1f6816219e917, 24f5135c7a9dfad0d6ac23d98d8b14100d1da51c

**Comment by mbstadler** [comment]
Fail rate filter (the maximal fraction of low-confidence modification calls in a read) was added in 10f1fa6b

**Comment by csoneson** [comment]
Included in #22

**Comment by csoneson** [comment]
Included in #22
