### ISSUE TITLE
addReadsSummary

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/footprintR#19]
- [x] change default value of keep.reads in addReadsSummary to TRUE (6c70984)
- [x] summary assays should be sparse arrays (ec236ca): Decided to leave the assays dense, because:
    - `Nmod`, `Nvalid` and `AvgConf` are dense because rowSums is based on `MatrixGenerics::rowSums`, which returns a (dense) numeric vector
    - `Nvalid` typically has few zeros, and the SparseArray version would be larger in memory than the dense one
    - `FracMod` and `Pmod` have to be calculated using dense matrices and would have to be converted back to sparse objects  (no `"/"` method for `SparseArray` objects, as the result wouldn't be sparse in general)
- [x] make sure that the output of readBedMethyl is consistent with the output of addReadsSummary (5fe339f)

**Comment by mbstadler** [comment]
I think this is done - feel free to reopen if you see  any remaining issues
