### ISSUE TITLE
Implement parallelization

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/footprintR#25]
- [ ] Sample entropy
- [x] readModBam
- [x] calcReadStats
- [ ] ...

**Comment by mbstadler** [comment]
Parallelization based on `BiocParallel::bpparam(..., BPPARAM)` has been added for `readModBam` in 689043ae and for `calcReadStats` in ae343b38

**Comment by mbstadler** [comment]
The C++ bam reading functions now also use multiple threads for de-compression of bam records (see e.g. f613c91 for read_modbam_cpp)
