### ISSUE TITLE
Construct summarized data directly from modbam

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/footprintR#27]
Something to ponder (currently not a priority) - we could directly construct summarized data (`Nmod` and `Nvalid`) while reading the modbam file (e.g. to create genome-wide summary matrices). Would this require having some filtering options in the reading function?

**Comment by mbstadler** [comment]
This was started in 13709dab23fa3fe3f203c13d1edef0a977033982 and is now implemented via `readModBam(..., level = "summary")`
